server:
  port: 8000
---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.114:3306/test
    username: root
    password: login
  profiles: default
security:
  user:
    password: weak
---
my:
   servers:
      - dev.bar.com
      - foo.bar.com
---
endpoints:
  shutdown:
    enabled: true